/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author adalberto
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        cmdGuardar.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdSalir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdentificacionCliente = new javax.swing.JTextField();
        txtSaldoActual = new javax.swing.JTextField();
        txtInteresAnual = new javax.swing.JTextField();
        txtNumeroCuenta = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmdBorrar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuenta ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos iniciales\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Saldo Actual");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("Interes Anual");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setText("ID Del Cliente");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel6.setText("No.De Cuenta");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        txtIdentificacionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionClienteActionPerformed(evt);
            }
        });
        txtIdentificacionCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdentificacionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, 30));

        txtSaldoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActualActionPerformed(evt);
            }
        });
        txtSaldoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoActualKeyTyped(evt);
            }
        });
        jPanel2.add(txtSaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 30));

        txtInteresAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInteresAnualActionPerformed(evt);
            }
        });
        txtInteresAnual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresAnualKeyTyped(evt);
            }
        });
        jPanel2.add(txtInteresAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 30));

        txtNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuentaActionPerformed(evt);
            }
        });
        txtNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCuentaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 230, 180));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdBorrar.setBackground(new java.awt.Color(255, 0, 0));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 30));

        cmdGuardar.setBackground(new java.awt.Color(204, 51, 255));
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        cmdActualizar.setBackground(new java.awt.Color(0, 0, 255));
        cmdActualizar.setText("Actualizar Saldo");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 30));

        cmdRetirar.setBackground(new java.awt.Color(0, 0, 255));
        cmdRetirar.setText("Retirar Saldo");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 30));

        cmdIngresar.setBackground(new java.awt.Color(0, 0, 255));
        cmdIngresar.setText("Ingresar Saldo");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 30));

        cmdMostrar.setBackground(new java.awt.Color(204, 51, 255));
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 30));

        cmdSalir.setBackground(new java.awt.Color(255, 255, 0));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel4.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 180, 310));

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Resultantes"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 360, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(786, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionClienteActionPerformed

    private void txtSaldoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActualActionPerformed

    private void txtInteresAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInteresAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInteresAnualActionPerformed

    private void txtNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        Cuenta c;
        txtResultado.setText("");
        txtInteresAnual.setText("");
        txtNumeroCuenta.setText("");
        txtIdentificacionCliente.setText("");
        txtSaldoActual.setText("");

        cmdGuardar.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdSalir.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (txtNumeroCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de  su cuenta");
            txtNumeroCuenta.requestFocusInWindow();
        } else if (Integer.parseInt(txtIdentificacionCliente.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "El número de Identificación del cliente no puede ser cero", "error", JOptionPane.ERROR_MESSAGE);
            txtIdentificacionCliente.requestFocusInWindow();
            txtIdentificacionCliente.selectAll();
        } else if (txtSaldoActual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su saldo actual,si su cuenta   no tiene saldo por favor ingrese 0");
            txtSaldoActual.requestFocusInWindow();
        } else if (txtInteresAnual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el interes anual");
            txtInteresAnual.requestFocusInWindow();
        } else {

            

            
            JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            cmdGuardar.setEnabled(false);
            cmdIngresar.setEnabled(true);
            cmdActualizar.setEnabled(false);
            cmdRetirar.setEnabled(true);
            cmdBorrar.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdSalir.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        Cuenta c;
       
        int cuenta,identi;
        double saldo,interes,actualizado;
        cuenta = Integer.parseInt(txtNumeroCuenta.getText());
        identi = Integer.parseInt(txtIdentificacionCliente.getText());
        saldo = Double.parseDouble(txtSaldoActual.getText());
        actualizado=Double.parseDouble(txtInteresAnual.getText());
        c = new Cuenta(cuenta, identi, saldo);
                JOptionPane.showMessageDialog(this, "Saldo actualizado correctamente");
                c.ActualizarSaldo(actualizado);
                txtSaldoActual.setText(c.renovar()); 
                txtResultado.setText(c.mostrar());
        
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdSalir.setEnabled(false);

        
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        Cuenta c;
        int cuenta,identi;
        double retir,saldo;
        cuenta = Integer.parseInt(txtNumeroCuenta .getText());
           identi = Integer.parseInt(txtIdentificacionCliente.getText());
           saldo = Double.parseDouble(txtSaldoActual.getText());
        c = new Cuenta(cuenta, identi, saldo);
         retir = Double.parseDouble(JOptionPane.showInputDialog(this, "Digite dinero a retirar"));
         if(retir>saldo){
             JOptionPane.showMessageDialog(this,"Saldo insuficiente, no se puede hacer el retiro","error",JOptionPane.ERROR_MESSAGE);
         }else{               
          c.Retirar(retir);
          txtResultado.append("\nSu saldo se ha actualizado a: " + retir+ "\n");
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdActualizar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdSalir.setEnabled(true);
        }
        
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        Cuenta c;
        int cuent,identi;
        double ingresos,saldo,saldonuevo;
        
         cuent = Integer.parseInt(txtNumeroCuenta.getText());
        identi = Integer.parseInt(txtIdentificacionCliente.getText());
        saldo = Double.parseDouble(txtSaldoActual.getText());
        c = new Cuenta(cuent, identi, saldo);
        ingresos = Double.parseDouble(JOptionPane.showInputDialog(this, "Dinero a ingresar en la cuenta"));
                        c.Ingresar(ingresos);
                    txtSaldoActual.setText(c.renovar());     
                txtResultado.setText(c.mostrar());
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdActualizar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdSalir.setEnabled(true);
       
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        Cuenta c ;
        int cuen,identificacion;
        double saldo,interes,actualizado;
        cuen = Integer.parseInt(txtNumeroCuenta.getText());
        identificacion = Integer.parseInt(txtIdentificacionCliente.getText());
        saldo = Double.parseDouble(txtSaldoActual.getText()); 
        c = new Cuenta(cuen, identificacion, saldo);
         txtSaldoActual.setText(c.renovar()); 
         txtResultado.setText(c.mostrar()); 
         
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdActualizar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdSalir.setEnabled(false);
        
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
     System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void txtNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCuentaKeyTyped
    char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtNumeroCuentaKeyTyped

    private void txtIdentificacionClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionClienteKeyTyped
   char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtIdentificacionClienteKeyTyped

    private void txtSaldoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoActualKeyTyped
     char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtSaldoActualKeyTyped

    private void txtInteresAnualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresAnualKeyTyped
       char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtInteresAnualKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdentificacionCliente;
    private javax.swing.JTextField txtInteresAnual;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtSaldoActual;
    // End of variables declaration//GEN-END:variables

    private double getSactual() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
